<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Routing\Route;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    /**
     * Retourne les article les plus récent
     * @param int $limit le nombre d'article à retourner
     * @Route("path")
     */
    public function findLatest($limit, Category $category = null, User $author = null) {
        $qb = $this->createQueryBuilder('a');

        $qb
                ->orderBy('a.id', 'DESC')
                ->setMaxResults($limit)

        ;
        if (!is_null($category)) {
            $qb->andWhere('IDENTITY(a.category)=' . $category->getId());
        }

        if (!is_null($author)) {
            $qb->andWhere('IDENTITY(a.author)=' . $author->getId());
        }
        return $qb->getQuery()->getResult();
    }

}
