<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username) {
        //dump($username);
        //m est l'alias de membre
        $qb = $this->createQueryBuilder('m');
        $qb
            ->where('m.pseudo = :pseudo')
            ->setParameter('pseudo', $username)
        ;
        $qb->setMaxResults(1);
        $query = $qb->getQuery();
        //dump($query->getSQL());
        $membre = $query->getOneOrNullResult();
        //dump($membre);die;
        return $membre;
    }

}
