<?php

namespace AppBundle\Repository;

/**
 * SalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleRepository extends \Doctrine\ORM\EntityRepository
{
        public function findVilles() {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->select('s.ville')
            ->distinct()
        ;
        
        $query = $qb->getQuery();
        //dump($query->getSQL());
        $result = $query->getScalarResult();
        
        $villes = [];
        
        foreach ($result as $row) {
            $villes[] = $row['ville'];
        }

        return $villes;
    }
}
