<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface {

    public function loadUserByUsername($username) {
        //u est l'alias de user
        $qb = $this->createQueryBuilder('u');
        $qb
            ->where('u.username = :username')
            ->orWhere('u.email = :username')
            ->setParameter('username', $username)
        ;
        return $qb->getQuery()->getOneOrNullResult();
    }

}
