app:
    resource: '@AppBundle/Controller/'
    type: annotation
 # toutes les routes de tous les controleur contenus
 
# dans le repertoire Admin seront préfixées par /admin   
admin:
    resource: '@AppBundle/Controller/Admin'
    type: annotation
    prefix: /admin
    
logout:
    path: /logout
    